mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



handler400  = 'mysite.views.bad_request'
handler403 = 'mysite.views.permission_denied'
handler404 = 'mysite.views.page_not_found'
handler500 = 'mysite.views.server_error'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    # path('account/', include('allauth.urls'))
    path('quiz/', include('quiz.urls', namespace='quiz')),
    # path('tenant/', include('tenant.urls', namespace='tenant'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.urls import path, re_path
from . import views
from django.views.generic import TemplateView   

app_name = 'quiz'

urlpatterns = [
 path('', views.QuizListView.as_view(),name='list'),
path('countdown/', views.countdown, name='countdown'),

#  path('list/', views.QuizListDisplayView.as_view(), name='quiz_list_detail'),
 path('create/', views.QuizCreateView.as_view(),name='create'),
 path('<slug:slug>/',views.QuizDetailView.as_view(), name='detail'),
 path('<slug:slug>/edit/', views.QuizUpdateView.as_view(), name='edit'),
 path('<slug:slug>/delete', views.QuizDeleteView.as_view(), name='delete'),
 path('<quiz_slug>/question/upload/', views.upload_question, name='upload_question'),
 path('<category_slug>/<quiz_slug>/take/', views.take_quiz, name='take_quiz'),
 path('<category_slug>/<quiz_slug>/completed/', views.quiz_completed, name='completed'),
#  path('<category_slug>/<quiz_slug>/list/', views.QuizListDisplayView.as_view(), name='quiz_list_detail'),
]

quiz/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
# from student.models import StudentProfile
from django.contrib.auth.models import User
from markdown_deux import markdown


class Category(models.Model):
    '''
    Model Name: Category
    Fields/Attributes  : category_title, slug, date_created, date_updated
            - category_title
                - the field for the category title
            - slug
                - the field for SEO url
            - date_created
                - the field that stores the date the category was created
            - date_updated
                - the field that stores the date the category was updated
    Methods: __str__
            - string representation of the model/class
            Meta:
                - verbose_name
                - verbose_name_plural

    Developer: Goodness Ezeokafor
    Date: 22nd December 2018
    '''
    category_title = models.CharField(
        max_length=255,
        blank=False,
        null=False,
        help_text='Category Title'
    )
    slug = models.SlugField(
        max_length=255,
        unique=True,
        help_text = 'Quiz Code, should be separated by dash e.g category-code',
        verbose_name='Quiz Code',
    )
    date_created=models.DateTimeField(
        auto_now_add=True
    )
    date_updated=models.DateTimeField(
        auto_now=True
    )

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.category_title

class Quiz(models.Model):
    '''
    Model: Quiz
    fields: title,slug,user,duration,marks, pass_marks, description,category, date_created,date_upadated
          - Title : Title of the quiz
          - Slug: SEO Url
          - Duration: Stores the time duration of the quiz
          - Marks : Mars awarded to each correct answer
          - Description: Quiz Description/Procedures,Rules
          - Category: A many to one relationship with the Category table, stores the category of the quiz
          - Date Created:the field that stores the date the category was created
          - Date Updated:the field that stores the date the category was updated
          - Meta
                - verbose_name
                - verbose_name_plural
                - default_permissions: default permissions
                - permission : custom permissions
        Methods:
            __str__: string representation of the model
            get_absolute_url: redirects
    Developer:Goodness Ezeokafor
    Date: 22nd December 2018
    '''
    title = models.CharField(
        unique=True,
        max_length=255,
        blank=False,
        null=False,
        help_text = 'Title of the quiz'
    )
    slug = models.SlugField(
        unique=True,
        max_length=255,
        help_text = 'Quiz Code, should be separated by dash',
        verbose_name='Quiz Code'
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete = models.CASCADE
    )
    duration = models.DurationField(
        max_length=255,
        blank=True,
        null=True,
        help_text ='Duration Of The Quiz: HH:MM:SS or 00:00:00'
    )
    # marks = models.IntegerField(
    #     blank=False,
    #     null=False,
    #     help_text = 'Marks to be awarded to each question'
    # )
    pass_mark = models.IntegerField(
        blank=False,
        null=False,
        help_text = 'Student Pass Mark'
    )
    description = models.TextField(
        default='Quiz description',
        help_text = 'Description for the quiz'
        )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE
    )
    publish = models.BooleanField(
        default=False,
        help_text='Tick if you want the quiz to be visible'
    )
    date_created = models.DateTimeField(
        auto_now_add=True,
    )
    date_updated = models.DateTimeField(
        auto_now=True
    )


    class Meta:
        verbose_name = 'Quiz/Exams'
        verbose_name_plural = 'Quizzes/Exams'
        default_permissions = ('add', 'change', 'delete')
        permissions =(
            ('take_quiz', 'Can Take Quiz'),
        )


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('quiz:detail', args = [self.slug])

    def get_take_quiz_url(self):
        return reverse('quiz:take_quiz', args=[self.category.slug, self.slug])

class Question(models.Model):
    '''
    Model Name: Question
    Fields : quiz, text, date_created, date_updated
    Methods:
         - __str_: string representation
    '''
    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
        # related_name = 'quest'

    )
    text = models.CharField(
        max_length=4000,
        blank=True,
        null=True
    )
    date_created = models.DateTimeField(
        auto_now_add=True
    )
    date_updated = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        verbose_name = 'Question'
        verbose_name_plural = 'Questions'
        ordering = ('id',)

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('quiz:question_list_view')
    

    def get_markdown(self):
        text = self.text
        return markdown(text)



class Answer(models.Model):
    question = models.ForeignKey(
        Question,
        on_delete = models.CASCADE,
        related_name = 'answers'
    )
    text= models.CharField(
        # 'Answer',
        max_length=255
    )
    is_correct = models.BooleanField(
        "Correct Answer",
        default=False
    )
    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Choices'


    
    # Methods

    # def get_score_percentage(self, quiz):
    #     '''
    #     # get the quiz marks
    #     # get the quiz pass mark
    #     total_score_percent = (total_right/total_score)* 100 
    #     '''
    #     total_score_percent = (self.total_right/self.total_score) * 100
    #     return total_score_percent

quiz/views.py
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from django.views.generic import DetailView,ListView
from .models import Quiz,Question,Category,Answer
from student.models import StudentProfile
from django.urls import reverse_lazy
from .forms import QuizCreateForm, TakeQuizForm
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from django.contrib import messages
from django.http import Http404, HttpResponse
from django.db.models import Q
from django.db import transaction
from student.models import TakenQuiz
from django.forms.utils import ValidationError
from time import localtime, strftime, sleep
import time

# email
from django.core.mail import send_mail


class QuizCreateView(LoginRequiredMixin,PermissionRequiredMixin,CreateView):
    '''
    Class Based View
        - for creating quiz
        - permission is required
    '''
    model = Quiz
    form_class = QuizCreateForm
    # success_url = reverse_lazy('quiz:detail') get_absolute_url defined in the model
    template_name = 'quiz/form.html'
    login_url = '/account/login/'
    permission_required = ('quiz.add_quiz', 'quiz.Add_quiz')
    raise_exception = True
    

    def form_valid(self,form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class QuizDetailView(LoginRequiredMixin,PermissionRequiredMixin,DetailView):
    '''
    Class Based View
        - for the detail
        - permission is required
    '''
    model = Quiz
    template_name = 'quiz/detail.html'
    slug_field = 'slug__iexact'  # slug field
    login_url = '/account/login/'
    permission_required = ('quiz.take_quiz')
    raise_exception = True
    

class QuizUpdateView(LoginRequiredMixin,PermissionRequiredMixin,UpdateView):
    '''
    Class Based View
        - for updating the quiz view
        - permission is required
    '''
    model = Quiz
    form_class = QuizCreateForm
    template_name = 'quiz/form.html'
    slug_field = 'slug__iexact'  # slug field
    login_url = '/account/login/'
    permission_required = ('quiz.add_quiz', 'quiz.delete_quiz', 'quiz.change_quiz')
    raise_exception = True
    
    def get_success_url(self):
        return reverse_lazy('quiz:detail', args=[self.object.slug])


class QuizDeleteView(LoginRequiredMixin,PermissionRequiredMixin,DeleteView):
    '''
    Cass Based View
        - for deleting quiz
        - permission is required
        - 
    '''
    model = Quiz
    template_name = 'quiz/quiz_confirm_delete.html'
    login_url = '/account/login/'
    permission_required = ('quiz.add_quiz', 'quiz.delete_quiz', 'quiz.change_quiz')
    raise_exception = True

    def get_success_url(self):
        '''
        Method that defines where this view will be redirected to 
        '''
        return reverse_lazy('quiz:list')



class QuizListView(LoginRequiredMixin,PermissionRequiredMixin,ListView):
    '''
    Class Based View
        - for listing view

    '''
    model = Quiz
    # queryset = Quiz.objects.filter(user=request.user)
    template_name = 'quiz/quiz_list.html'
    login_url = '/account/login/'
    permission_required = ('quiz.take_quiz')
    raise_exception = True
    
    def get_queryset(self):
        return super(QuizListView,self).get_queryset().filter(Q(user=self.request.user) | Q(publish=True))




@permission_required('quiz.add_question', raise_exception=True)
def upload_question(request,quiz_slug=None):
    '''
    View for uploading the question
    '''
    quiz = get_object_or_404(Quiz,slug=quiz_slug)
    template_name = 'question/upload_question.html'
    if request.method == 'POST':
        csvfile = request.FILES['questionfile']  # gets the input field name
        print(csvfile.name)  # prints the csv file name
        if not csvfile.name.endswith('.csv'):
            print("Invalid!!") # prints invalid at the console
            messages.errors(request, "CSV file format not supported")
            return(HttpResponseRedirect('quiz:fail'))
        file_data = csvfile.read().decode("utf-8")  # reads the csv file
        # print(file_data)
        lines = file_data.split("\n") # split using the delimiter
        data_dict = {} # empty dictionary to store the csv data
        print(len(lines))
        for line in lines:
            print(line)
            fields = line.split(',')
            # print(fields)
            data_dict = {
                'question_text':fields[0],
            }
            # print(len(data_dict))
            if data_dict != '':
                question = Question.objects.create(
                    quiz=quiz,
                    text=data_dict['question_text']
                )
                # question.quiz = quiz
                # question.date_created = timezone.now()
                # question.date_upadated= timezone.now()
                # question.save()
                messages.success(request, "File Successfully Uploaded")
                # return HttpResponseRedirect(reverse('quiz:upload_successful'))
            else:
                messages.errors(request, "File not uploaded")
    context = {'quiz':quiz}
    return render(request, template_name, context)



@login_required(login_url='/account/login/')
@permission_required('quiz.take_quiz', raise_exception=True)
def take_quiz(request, category_slug=None,quiz_slug=None):
    question_no = 0
    quiz = get_object_or_404(Quiz,slug=quiz_slug)
    category = get_object_or_404(Category,slug=category_slug)
    try:
        student = StudentProfile.objects.get(user=request.user)
    except:
        raise Http404("You Can't take quiz!!.Please contact your invigilator!!")

    context = {}
    if student.quizzes.filter(slug=quiz_slug).exists():
        '''
            if the student has taken the quiz 
            redirects him/her to the taken_quiz view 
        '''
        raise Http404("You have already taken the quiz!!")
        # return render(request, 'quiz/taken_quiz.html')

    print(student)
    total_questions = quiz.question_set.count()
    unanswered_questions = student.get_unanswered_questions(quiz)  # gets the total unanwered questions
    total_unanswered_questions = unanswered_questions.count()  # counts the total unanswered questions
    try :
        progress = 100 - round(((total_unanswered_questions - 1) / total_questions) * 100) # remeber to catch the Division By Zero error
        print(progress)
    except ZeroDivisionError:
        raise ValidationError("An Issue Has Occured, Please Inform Your Invigilator!!")
    question = unanswered_questions.first()  # gets the first questioin
    if request.method == 'POST':
        form = TakeQuizForm(question=question, data=request.POST)
        question_no += 1
        if form.is_valid():
            print(question_no)
            with transaction.atomic():    
                student_answer = form.save(commit=False) # create a false commit
                student_answer.student = student # sets the currently logged in user
                student_answer.save() # saves to the the Student
                if student.get_unanswered_questions(quiz).exists():
                    # return render(request, 'quiz/take_quiz.html', {'question_no':question_no})
                    return redirect("quiz:take_quiz", category_slug, quiz_slug)
                else:
                    correct_answers = student.quiz_answers.filter(answer__question__quiz=quiz,answer__is_correct=True).count()
                    print(correct_answers)
                    score = round((correct_answers/total_questions) * 100.0, 2)
                    TakenQuiz.objects.create(
                        student=student,
                        quiz=quiz,
                        score=score
                    )
                    if score <  quiz.pass_mark:
                        # messages.warning(request, 'Sorry!!')
                        messages.warning(request, 'Better luck next time! Your score for the quiz %s was %s.' % (quiz.title, score))

                    else:
                        # messages.success(request, 'Congratulations!!!')
                        messages.success(request, 'Congratulations! You completed the quiz %s with success! You scored %s points.' % (quiz.title, score))

                    return redirect('quiz:completed', category_slug, quiz_slug)
    else:
        form = TakeQuizForm(question=question)
    # for i  in range(total_questions):
    #     question_no = i
    return render(request, 'quiz/take_quiz.html',{
        'quiz':quiz,
        'question':question,
        'form':form,
        'progress':progress,
        'total_questions':range(1,total_questions+1),
        'question_no':question_no
    })


def quiz_completed(request, category_slug, quiz_slug):
    username = request.user.username  # get the current user username
    user = User.objects.get(username=username)  # gets the current user
    student = StudentProfile.objects.get(user=request.user)  # gets the user student rofile
    quiz = get_object_or_404(Quiz, slug=quiz_slug)
    #email
    # student_email = user.email  # the user email
    # examiner_email = 'gootech442@gmail.com'  # examiner email
    # subject_email = "ISEP CBT QUIZ"
    student_quiz_result = TakenQuiz.objects.get(student=student)
    # print(type(quiz.pass_mark))
    # print(type(student_quiz_result.score))
    # if student_quiz_result.score >= quiz.pass_mark:
    #     messages.success(request, 'Congratulations! ')
    # else:
    #     messages.error(request, "Sorry!!")
    # message = "Your Result Score {}".format(student_quiz_result.score)
    # print(student_email)

    # if subject_email:
    #     send_mail(subject_email, message, examiner_email, [student_email])
    template_name = 'quiz/completed.html'
    context = {

quiz/templates/quiz/completed.html
{% extends 'account/base.html' %}
{% block content %}
<div id="page-wrapper">
    <div class="row">
        <h3>Thanks For Completing The Quiz</h3>
        {% if messages %}
            {% for msg in messages %}
                <h3>{{ msg }}</h3>
            {% endfor %}
        {% endif %}
        
</div>
{% endblock %}

quiz/templates/quiz/detail.html
{% extends 'account/base.html' %}
{% block content %}
<div id="page-wrapper">
    <div class="row">
        <div class="contianer-fluid">
            <h4>Title: {{ object.title}}</h4>
            <h4>Examiner: {{ object.user.first_name }} {{object.user.last_name}}</h4>
            <h4>Duration: {{ object.duration}}</h4>
            <h4>Marks: {{object.marks}} marks each</h4>
            <h4>Pass Mark: {{ object.pass_mark}}</h4>
            <h4>Date Created: {{ object.date_created }}</h4>
            <h4>Description: {{ object.description }}</h4>
            <h5>
                {% if perms.quiz.add_quiz %}
                <a href="{% url 'quiz:upload_question' quiz.slug%}">Upload Question</a>
                <a href="{% url 'quiz:edit'  quiz.slug %}">Edit Quiz</a>
                <a href="{% url 'quiz:delete' quiz.slug %}">Delete Quiz</a>
                {% endif %}
            </h5>                
            {% if perms.quiz.take_quiz %}
            <h5><a href="{% url 'quiz:take_quiz' quiz.category.slug quiz.slug %}">Take Quiz</a></h5>
            {% endif %}
        </div>    
    </div>
</div>
{% endblock %}

quiz/templates/quiz/form.html
{% extends 'account/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    {% if object %}
        {{ block.super }} | Edit '{{bject.title}}'
    {% else %}
        {{ block.super }} | Create
    {% endif %}
{% endblock %}
{% block head_extra %}
    {{ form.media }}
{% endblock %}
{% block content %}

<div id="page-wrapper">
    <div class="row">
        <div class="col-md-7">
            <h3>
            {% if object %}
            Edit '{{ object.title }}' 
            {% else %}
            Create Quiz
            {% endif %}
            </h3>
            <hr />
            <form action="#" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-lg ">
                {% if object %}    
                    Edit
                {% else %}
                    Create
                    {% endif %}
            </button>
            </form>
        </div>

    </div>
</div>

{% endblock %}

quiz/templates/quiz/list.html
{% extends 'base.html' %}
{% block content %}



<div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                DataTables Advanced Tables
                </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead>
                    <tr>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Username</th>
                        <th>Email</th>
                        <th>Image</th>
                    </tr>
                    </thead>
                    {% if object_list %}
                    <tbody>
                    {% for student in object_list %}
    
                    <tr class="odd gradeX">
                            <td>
                                <a href="{{ student.get_absolute_url }}">
                                        {{ student.user.first_name }}
                                </a>
                            </td>  
                            <td>
                                <a href="{{ student.get_absolute_url }}">
                                    {{ student.user.last_name }}    
                                </a>
                            </td>
                            <td>
                                <a href="{{ student.get_absolute_url }}">
                                    {{ student.user.username }}
                                </a>
                            </td>    
                            <td class="center">{{ student.user.email }}</td>
                            <td class="center"><img src="{{ student.photo.url }}" alt="No Image" width="50" height="50"></td>        
                    </tr>
                    {% endfor %}
    
                    </tbody>
                    {% endif %}
                </table>
    <div class="well">
    <h4>DataTables Usage Information</h4>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam corrupti cum, saepe eligendi debitis, quis nam quos impedit molestias
         quaerat aspernatur, ipsam rerum. Omnis fuga, illo earum reprehenderit numquam deserunt?</p>
    <a class="btn btn-default btn-lg btn-block"  href="{% url 'account:student_profile:register'%}">
        Add Student
    </a>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
{% comment %}
{% if quizzes %}
    {% for quiz in quizzes %}
       <a href="{% url 'quiz:detail' quiz.slug %}">{{ quiz.title }}</a> 
        <br>
    {% endfor %}
{% endif %}

{% endcomment %}

{% endblock %}

quiz/templates/quiz/olddetail.html
{% extends 'base.html' %}
{% block content %}
<h3>{{ quiz.title }} Details</h3>
<p>
    Title : {{ quiz.title }}
</p>
<p>
        Examiner : {{ quiz.creator }}

</p>
<p>
    Category : {{ quiz.category}}
</p>
<p>
    Date Created : {{ quiz.date_created }}
</p>
<p>
    Pass Mark : {{ quiz.pass_mark }}
</p>
<button type="button">
    <a href="{% url 'quiz:take_quiz' quiz.category quiz.slug %}" onclick="alert('hello world')">
        Take Quiz
    </a>
</button>
{% endblock %}

quiz/templates/quiz/quiz_confirm_delete.html
{% extends 'account/base.html' %}
{% block title %} 
    {% if object %}
        Delete '{{ object.title }}'
    {% endif%}
{% endblock %}
{% block content%}
<div id="page-wrapper">
    <div class="row">
        <div class="container-fluid">
        <form action="" method="POST">
                {% csrf_token %}
           <h3>Do you really wat to delete "{{ object }}"</h3> 
            <button type="submit">Yes, remove it</button>   
            </form>
        </div>
    </div>
</div>
{% endblock %}

quiz/templates/quiz/quiz_list.html
{% extends 'account/base.html' %}
{% block content %}
<div id="page-wrapper">
<div class="row">
   <div class="col-lg-12">
        
        {% if object_list %}
        <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Quiz Created By You</h4>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                <tr>
                    <th>Quiz Title</th>
                    <th>Subject</th>
                    <th>Quiz Duration</th>
                    <th>Examiner</th>
                </tr>
                </thead>
            <tbody>
                    {% for quiz in object_list %}
                    <tr class="odd gradeX">
                            <td>
                                <a href="{{ quiz.get_absolute_url }}">
                                        {{ quiz.title }}
                                </a>
                            </td>  
                            <td>
                                    {{ quiz.category }}    
                                
                            </td>
                            <td>
                                    {{ quiz.duration }}
                            </td>    
                            <td class="center">{{ quiz.user }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
                {% else %}
                    {% if perms.quiz.add_quiz %}
                        <div class="create-quiz" style="margin-top:50px">
                            <a href="{% url 'quiz:create' %}" class="btn btn-success">Create Quiz</a>
                        </div>
                    {% endif %}
                    {% if perms.quiz.take_quiz %}
                        <div>
                            <a href="">Sorry No Quiz Yet</a>
                        </div>
                    {% endif %}
                {% endif %}    
    </div>
</div>
</div>
</div>
</div>

{% endblock %}

quiz/templates/quiz/take_quiz.html
{% extends 'account/base.html' %}
{% load crispy_forms_tags %}
{% load markdown_deux_tags %}


{% block content %}
<div id="page-wrapper">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-7" style="margin-top:100px;">
                <div class="progress ">
                        <div class="progress-bar" role="progressbar" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress }}%"></div>
                </div>
                <h1 class="card-title">{{ quiz.name }}</h3>           
                    {% for quest in total_questions %}
                        {{ quest }}
                    {% endfor %} 
                {% if question %}
            <div class="list-group">
                <h3>{{ question.get_markdown|safe }} <small>Progress: {{ progress }}% out of 100</small></h3>
                <form method="POST" novalidate>
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" id="btn" class="btn">Next</button>
                    </form>
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

quiz/templates/quiz/taken_quiz.html
<h1>Quiz Allready Taken </h1>